<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 5/18/17
 * Time: 11:31 AM
 */

namespace pastuhov\ymlcatalog\categories\models;


use yii\base\Exception;
use yii\db\ActiveRecord;

class Category extends base\Category
{
    protected static $cache = [];
    public static function find()
    {
        return new \pastuhov\ymlcatalog\categories\models\queries\Category(self::class); // TODO: Change the autogenerated stub
    }

    public static function findOrCreate($attributes) {
        $extId = $attributes['id'];
        $result = self::getRecordFromCacheByExtId($extId);

        if (empty($attributes['parent'])) {
            $parentId = null;
        } else {
            $parent = self::getRecordFromCacheByExtId($attributes['parent'], false);
            if (!$parent) {
                throw new Exception('Parent for record ' . var_export($attributes, true) . ' is not found');
            }

            $parentId = $parent->id;
        }

        $result->attributes = [
            'ext_char_id' => $attributes['id'],
            'full_name' => $attributes['fullName'],
            'name' => $attributes['name'],
            'line_nbr' => $attributes['line'],
            'ymlcatalog_categorie_id' => $parentId,
        ];

        return $result;
    }

    /**
     * @param $extId
     * @return array|null|Category|ActiveRecord
     */
    public static function getRecordFromCacheByExtId($extId, $isCreate = true)
    {
        if (isset(self::$cache[$extId])) {
            return self::$cache[$extId];
        }

        $result = self::find()->byExtCharId($extId)->one();

        if ($isCreate && !$result) {
            $result = new self;
        }

        if ($result) {
            self::$cache[$extId] = $result;
        }

        return $result;
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        foreach ($this->attributes as $attribute => $value) {
            if ($this->isAttributeChanged($attribute)) {
                return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
            }
        }

        return false;
    }
}