<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 5/18/17
 * Time: 3:03 PM
 */

namespace pastuhov\ymlcatalog\categories\models\yml;


use pastuhov\ymlcatalog\BaseFindYmlInterface;
use pastuhov\ymlcatalog\CategoryInterface;
use pastuhov\ymlcatalog\categories\models\Category as CategoryModel;

class Category extends CategoryModel implements CategoryInterface, BaseFindYmlInterface
{
    public static function find()
    {
        return new \pastuhov\ymlcatalog\categories\models\queries\Category(self::class); // TODO: Change the autogenerated stub
    }
    /**
     * Название категории.
     *
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Идентификатор категории товаров.
     *
     * Идентификатор категории должен быть уникальным положительным целым числом. Ни у одной категории параметр id не
     * может быть равен «0»
     *
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Идентификатор более высокой по иерархии (родительской) категории товаров.
     *
     * Если элемент <parentId> не указан, то категория считается корневой.
     *
     * @return int|null
     */
    public function getParentId() {
        return $this->ymlcatalog_categorie_id;
    }

    /**
     * @param array $findParams Массив дополнительных параметров для поиска.
     *
     * @return \yii\db\ActiveQuery
     */
    public static function findYml($findParams = []) {
        return self::find();
    }
}